spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Gs123@8027
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8082'
Welcome:
  Message: Welcome to My First REST API !!!